### PR TITLE
Add global usage instructions to README

### PR DESCRIPTION
**Pull request by shadowhand**
Useful when you want to use the hooks to validate changes in forks of projects.

### CODE REVIEW

**Comment by shadowhand** [comment]
Ah, after using this, it looks like some of the Process commands do not work as expected because they specify `vendor/bin/` which does not resolve properly when using global installation. Some kind of relative comparison is needed.

**Comment by sjparkinson** [comment]
Yep, there was mention of using global tools alongside those in `vendor/bin` in #27.

I see a few options:

- [ ] Only use tools in the $PATH
- [ ] Expose `getProjectBase` as a public method on `VersionControlInterface`
- [ ] Pass in the project's base path into the `StaticReivew` class as configuration

**Comment by keradus** [comment]
IMO `getProjectBase` shouldn't be used to determine location of global tools...

**Comment by keradus** [comment]
maybe simple use `composer global show -i` to determine if tool is installed globally via composer ?

**Comment by sjparkinson** [comment]
@shadowhand going to close this for now.

**Comment by keradus** [comment]
:(

**Comment by shadowhand** [comment]
@sjparkinson I'd like to see this happen sooner rather than later. Do you think we could use a comparison of `__DIR__` in `StaticReivew` with `getcwd()` to determine if we are in global mode?

**Comment by sjparkinson** [comment]
> I'd like to see this happen sooner rather than later. Do you think we could use a comparison of __DIR__ in StaticReivew with getcwd() to determine if we are in global mode?

That's a good idea, I haven't sat down to think about this issue much yet but would love to resolve it.

**Comment by keradus** [comment]
Then, if we all agreed that this would be nice and we want to have it - why the issue has been closed?

**Comment by shadowhand** [comment]
Reopening this, now that we know it is possible.

**Pull request merged**
